### ISSUE TITLE
Game:GetItemHistory returns unusable userdata.

### ISSUE THREAD

**Issue by Meowlala** [Meowlala/RepentanceAPIIssueTracker#1]

**Comment by im-tem** [comment]
Wasn't this method removed from the game?
![image](https://user-images.githubusercontent.com/18075164/117050054-988d8380-ad1d-11eb-9160-6dc4170d9936.png)

**Comment by Meowlala** [comment]
Since this function doesn't exist, closing and referencing #67 instead.
