### ISSUE TITLE
Crashes on save file select after exiting a run as a custom character and then disabling the mod it is from

### ISSUE THREAD

**Issue by spikeof2010** [Meowlala/RepentanceAPIIssueTracker#100]
After subscribing to a character mod and starting a game with it, exiting and restarting the game with the mod unsubscribes crashes the game to desktop upon file select.

I don't think the mods I used in this instance matters, more so I think the game's crashing due to not being able to pull a character icon for the in progress run (I.e. It tried to load Ohyo's character sprite with nothing to load).

Mods used:
EID (Likely not the issue)
Mod Compatibility Hack
Ohyo (The character in question)

**Comment by Meowlala** [comment]
Just remembered that this duplicates #32, will close and redirect to there.
