### ISSUE TITLE
Steam achievements disabled while mods are on; in-game unlocks will still work

### ISSUE THREAD

**Issue by bobatealee** [Meowlala/RepentanceAPIIssueTracker#102]
When mods are enabled, any new achievements unlocked will be granted as normal in-game, but will not be granted through Steam. In Afterbirth+, achievements were granted both in-game and through steam with mods on.

This does not seem to be the case when mods are disabled.

**Comment by Meowlala** [comment]
Should be fixed in the hotfix for rep's first API patch. Closing, but will reopen if reproducible.
