### ISSUE TITLE
Two new DamageFlag suggestions.

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#121]
**DamageFlag.DAMAGE_KEEP_DEVIL**

Right now the only flag we have that deals damage to soul hearts and red hearts but doesn't decrease devil deal chance is the Curse Room flag, which is a bit constricting considering a bunch of mods give curse room immunity, and even the base game does with a trinket.

I'd be nice to have a flag like this to make custom damaging props that don't get rid of your devil deal chance, preferably.

**DamageFlag.DAMAGE_SAFE**

I could not come up with an intuitive name that wasn't hyper long, but the point of this flag is that any TakeDamage call that has it, will make it so the damage doesn't break Glass Cannon.

**Comment by Meowlala** [comment]
The new `DamageFlag.DAMAGE_NO_PENALTIES` that was added in rep covers both of these cases.

**Comment by AgentCucco** [comment]
Wait I swear I didn't find this in the enums, am I just that blind.
