### ISSUE TITLE
Include does not work inside of included files

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#124]
Whlie the primary usage of loading extra lua code may not be obviously useful, the secondary use of having a file return data is. For example, a lua file containing a long list of layouts would be convenient to include from within the file that wants to use them, instead of having to do it in main.lua

**Comment by Meowlala** [comment]
I can't reproduce this, can you send an example?

**Comment by Xalum** [comment]
I've messed around with the mod and realised the issue I was having is that the path include looks for always starts at the main.lua folder, instead of the relative position of the file it's run from
so if you do `include("lua/foo")` and want to include a file in lua/meta/
you have to do `include("lua/meta/bar")` regardless of if you're in main.lua or foo.lua

**Comment by Meowlala** [comment]
This is consistent with require, right?

**Comment by Xalum** [comment]
Yes it appears to be; guess I'd just never used require in that way and didn't realise
