### ISSUE TITLE
Hotkey for toggling FadedConsoleDisplay on and off

### ISSUE THREAD

**Issue by Meowlala** [Meowlala/RepentanceAPIIssueTracker#129]
FadedConsoleDisplay is very useful for debugging, but can also be too obstructive in certain cases, such as error spam or when debugging things that update frequently. A hotkey or method to implement a hotkey would be very nice, as currently it's impossible to toggle without editing options.ini and relaunching the game.

**Comment by AgentCucco** [comment]
I feel like a hotkey might be a bit unnecessary, a debug command would work almost as well.

**Comment by Meowlala** [comment]
This is now possible to implement with a mod as of 1.7.6
