### ISSUE TITLE
TearFlags above TEARFLAG(63) are impossible to add to, remove from, or detect upon tears

### ISSUE THREAD

**Issue by Meowlala** [Meowlala/RepentanceAPIIssueTracker#151]
Easily reproduced by giving yourself Knockout Drops and activating debug 9, then shooting and testing the following commands:

`lua Isaac.FindByType(2)[1]:ToTear():ClearTearFlags(TearFlags.TEAR_PUNCH)`

`lua print(Isaac.FindByType(2)[1]:ToTear():HasTearFlags(TearFlags.TEAR_PUNCH))`

Or without knockout drops:

`lua Isaac.FindByType(2)[1]:ToTear():AddTearFlags(TearFlags.TEAR_PUNCH)`

This applies to any tear flag that is defined in enums.lua with `TEARFLAG()` using a number higher than 63, including Lodestone, Mucormycosis, Ocular Rift, Uranus, etc.

**Comment by Meowlala** [comment]
This can be mostly fixed by changing the `TEARFLAG` function from

`return x >= 64 and BitSet128(0,1<<x) or BitSet128(1<<x,0)`

to

`return x >= 64 and BitSet128(0,1<< (x - 64)) or BitSet128(1<<x,0)`

**Comment by Sinsthar** [comment]
Good find, I've been trying to find a solution just before you opened this issue !

**Comment by UnderscoreKilburn** [comment]
Wow that was a brain fart alright, nice find!

**Comment by Meowlala** [comment]
Confirmed fixed in 1.7.5.
