### ISSUE TITLE
An EntityPickup method to know from which pool it was pulled from.

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#156]
It'd be useful to have something like this to make duplicates of items or do funnies with itempools in general. Right now the closest thing we have is ItemPool:GetPoolForRoom(), however this has a few flaws since as the name implies, it gets the pool for the room, so if you open a red chest in a boss room for example, it will still return the boss pool rather than the red chest.

**Comment by Meowlala** [comment]
Duplicates #67
