### ISSUE TITLE
room:TryMakeBridge() and gridpit:MakeBridge() seem to be broken

### ISSUE THREAD

**Issue by Erfly** [Meowlala/RepentanceAPIIssueTracker#157]
Despite passing a gridentity (whether by itself or :ToPit() makes no difference) to the former, and passing nothing in the latter, they both complain about how they got a table instead of a gridentity

**Comment by Meowlala** [comment]
Both of these functions work, they just have undocumented changes. `GridPit:MakeBridge()` is now `GridPit:MakeBridge(GridEntity)` and will work if passed any grid entity, including itself. `Room:TryMakeBridge(GridEntity)` is now `Room:TryMakeBridge(GridEntity, GridEntity)` and will work if passed 2 grid entities, the first of which being a pit and the second being anything, including the same pit.

**Comment by Erfly** [comment]
even if this works it seems strange to have to pass a random entity that does nothing

**Comment by Meowlala** [comment]
I think the second grid entity is meant to define which bridge type should be used if it's a rock or spiked rock?
