### ISSUE TITLE
GetOverlay Function for Sprites

### ISSUE THREAD

**Issue by jsgnextortex** [Meowlala/RepentanceAPIIssueTracker#201]
The new GetAnimation function for sprites is really good, but a lot of entities use overlays for some of their key visual elements, heads for the most part, so a GetOverlay animation is pretty much needed for some aplications.

**Comment by Xalum** [comment]
This function already exists by a different name, :GetOverlayAnimation()
![image](https://user-images.githubusercontent.com/43268652/120051821-307b4600-c01a-11eb-8fb0-fb931fddbe8c.png)

**Comment by jsgnextortex** [comment]
I'm stupid...
