### ISSUE TITLE
Crash while attempting to remove an entity when entering a room

### ISSUE THREAD

**Issue by StrangeWergon** [Meowlala/RepentanceAPIIssueTracker#219]
```
local mod = RegisterMod("Crash Example", 1);

function mod:changeRoom()
	local room = Game():GetLevel():GetCurrentRoom()

	local entities = room:GetEntities()
	for i = 1, entities.Size do
		local ent = entities:Get(i)
		if ent ~= nil then
			ent:Remove()
		end
	end
end

mod:AddCallback(ModCallbacks.MC_POST_NEW_ROOM, mod.changeRoom)
```

Try to enter several rooms, then restart (hold "R" button), enter several rooms again. You will get crash very quickly.

**Comment by Zamiell** [comment]
Don't use room:GetEntities(), use Isaac.GetRoomEntities().
Making this change will likely stop your crashing.

Furthermore, you are using the wrong callback for this task.
If you want to stop entities from spawning, use the PreEntitySpawn callback.

**Comment by StrangeWergon** [comment]
@Zamiell, Yes, I know about **MC_PRE_ENTITY_SPAWN** and **MC_PRE_ROOM_ENTITY_SPAWN**. I'm agree that this process should rather be done there. But this doesn't in any way negate the fact that there shouldn't be a crash. I believe that the modder shouldn't be able to cause a crash through the LUA.

Btw, _Isaac.GetRoomEntities()_ doesn't stop the crash.

**Comment by Meowlala** [comment]
There are a couple of problems with this callback. For one, it doesn't check that an entity is safe to remove, so it could even remove players, which inevitably crashes the game.

I agree that it shouldn't be possible to cause crashes through lua ideally, but it's worth keeping in mind that there are a lot of ways to crash the game currently and this one is fairly unlikely with best practices.
