### ISSUE TITLE
Continuing a run on a floor with a room added through mods can crash the game

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#227]
If you attempt to continue a run, and you are on a floor with a modded room in it, the game has a chance to crash. This is replicated by doing the following:

1. Create a mod with nothing in it but a Basement rooms STB file, located in "content/rooms". The rooms in the file can be empty or otherwise. Room IDs seem to have no effect.
2. Start a run on Basement I.
3. Explore the floor until you find a custom modded room (to confirm the floor has one).
4. Exit the run and continue.

Do note that this does not seem to be a consistent crash, but the above method has proven to be capable of creating the conditions where a crash can occur; the chance seems to go up with the number of custom rooms on the floor. Do also note that  the above test was performed with empty custom rooms with no doors disabled at difficulty 5, on Basement I in hard mode. Room IDs tested were those starting at the IDs the game ended at (1096+) and at higher IDs (17000+).

**Comment by Erfly** [comment]
Modded rooms also easily creates a crash with glowing hourglass and the backwards path

**Comment by namishere** [comment]
Problem still exists as of patch v1.7.5

**Comment by Meowlala** [comment]
Appears to have been fixed in 1.7.6
