### ISSUE TITLE
A new EntityFlag to make enemies not shut down doors.

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#236]
Right now (to my knowledge) the only way to make enemies not close doors when in a room is by changing their ``shutdoors`` attribute in the xml.

There are some item ideas and general stuff I'd like to do which revolves around making enemies not shut the doors anymore under certain conditions, but there doesn't seem to be a way to do that via lua.

Something like EntityFlag.FLAG_DONT_SHUT_DOORS or the like could be pretty useful for these situations.

**Comment by Meowlala** [comment]
You can do this by setting `entity:ToNPC().CanShutDoors = false`

**Comment by AgentCucco** [comment]
Wh, we can do that, lol

**Comment by AgentCucco** [comment]
Oh yeah I guess you can shut down this issue due to being invalid or something like that.
