### ISSUE TITLE
Method to change sprite animation speed

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#239]
Currently, there are a few effects in the basegame that are capable of affecting the animation speed of entities (slow status, Stop Watch, I'm Excited, etc.). It would be useful to have the ability to affect the animation speed in a manner similar to these basegame effects through the API.

**Comment by Meowlala** [comment]
Is this not what `Sprite.PlaybackSpeed` does?

**Comment by AgentCucco** [comment]
Yep that's pretty much it, it's what we even used before to skip frames before the function was fixed in rep, lol.

**Comment by TaigaTreant** [comment]
Ah, must've missed that. Thanks.
