### ISSUE TITLE
[Repentance] Using Entity:ToTear() will crash the game?

### ISSUE THREAD

**Issue by epfly6** [Meowlala/RepentanceAPIIssueTracker#25]
Used this function inside MC_FAMILIAR_UPDATE callback with Isaac.Spawn(). Removing ToTear() will not trigger crash.
Possily need more researching?

**Comment by UnderscoreKilburn** [comment]
Can you post the exact code?

**Comment by epfly6** [comment]
> Can you post the exact code?

Tried to replicate tthis with testing familiar, and it works fine, but here is the code for familiar one anyway. Probably something in main mod causing crash then 

https://pastebin.com/RU5vEkFJ - familiar code
https://pastebin.com/Fka9cpL0 - snippet from main.lua

**Comment by Meowlala** [comment]
Closing this until the actual issue can be found, if there is one.
