### ISSUE TITLE
No methods for detecting Red Key rooms

### ISSUE THREAD

**Issue by pedroff1** [Meowlala/RepentanceAPIIssueTracker#258]
There are no known functions or attributes capable of detecting whether a given room was generated after level generation by Red Key, Cracked key, "The Moon?" or Soul of Cain. 
Only Currently known method of knowing is by manually keeping track of all rooms generated on new level and then comparing the index of the current room with said room list.

**Comment by Gemboat** [comment]
This was added as an undocumented feature in one of the patches.
`Game():GetLevel():GetCurrentRoomDesc().Flags & RoomDescriptor.FLAG_RED_ROOM > 0` can tell whether the current room is or is not a red room, and the same method can easily be applied to other rooms too.
