### ISSUE TITLE
Allow getting the animation name of the animation that a sprite is currently playing

### ISSUE THREAD

**Issue by DarkestSentinel** [Meowlala/RepentanceAPIIssueTracker#28]
A Sprite:GetCurrentAnimation() function would make life a lot easier as Sprite:IsPlaying() or Sprite:IsFinished() requires you to know which animations that specific entity can even play. This is especially troublesome when you need to work with entities of which you don't necessarily know which type they'll be, or if that entity in question has a lot of similar but differently named animations for which you need to check, resulting in a long chain of Sprite:IsPlaying() statements or a for loop checking for lots of different animations

**Comment by Meowlala** [comment]
Fixed in the first repentance API patch, with `Sprite:GetAnimation()`
