### ISSUE TITLE
Room.TrySpawnRepentanceDoor() missing

### ISSUE THREAD

**Issue by Zamiell** [Meowlala/RepentanceAPIIssueTracker#282]
There are `TrySpawnXDoors()` functions for every type of door except for Repentance doors, so this method needs to be added for consistentcy.

The lack of this method is incredibly painful as it means that Repentance doors have to be recreated from scratch.

**Comment by epfly6** [comment]
Added in 1.7.5 as method Room.TrySpawnSecretExit https://wofsauge.github.io/IsaacDocs/rep/Room.html?#tryspawnsecretexit.
Please close this issue
