### ISSUE TITLE
MC_PRE_USE_CARD and MC_PRE_USE_PILL

### ISSUE THREAD

**Issue by kittenchilly** [Meowlala/RepentanceAPIIssueTracker#309]
We have a MC_PRE_USE_ITEM but not a pre callback for any of the other use callbacks.
It is currently really hard, if not impossible to stop a card or pill effect from happening without these. Adding these would give more freedom in allowing custom effects for existing cards and pills, like with MC_PRE_USE_ITEM.

**Comment by Xalum** [comment]
duplicates #70
