### ISSUE TITLE
New callback for detecting when an item is gained

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#315]
Sometimes we want to perform an action when you gain a collectible, such as granting pickups not compatible with items.xml, or setting data tags on the player. Typically, this can just be handled through checking GetCollectibleNum or reading the EntityPlayer.QueuedItem attribute, however this is not sufficient for active items, which can be dropped and regained, and does not work when playing as Tainted Isaac, where the same can be done for passive items.

A new MC_POST/PRE_GAIN_COLLECTIBLE callback, passing you (CollectibleType, CollectibleRNG, EntityPlayer, bool : FirstPickup, bool : FromReroll), and taking CollectibleType as an optional parameter would be ideal

**Comment by Xalum** [comment]
* An equivalent for trinkets would be nice too

**Comment by Meowlala** [comment]
Doing some cleanup, this duplicates #215.
