### ISSUE TITLE
Player Render callback runs twice in water-filled rooms.

### ISSUE THREAD

**Issue by SonioExpert46** [Meowlala/RepentanceAPIIssueTracker#316]
Printing the player's FrameCount versus Isaac.GetFrameCount, first without and then within a water-filled room. Downpour, using Flush!, etc.
![image](https://user-images.githubusercontent.com/7707552/134115910-395c12ad-ce02-4fcd-8e35-0d1a9ba4f3f6.png)

![image](https://user-images.githubusercontent.com/7707552/134115889-aa6e8914-436d-4445-bb0a-a11a01fff447.png)

**Comment by Meowlala** [comment]
This is normal. One of the render passes is the reflection pass, goes for all reflected entities.
