### ISSUE TITLE
TrinketType for Short Fuse is named differently

### ISSUE THREAD

**Issue by AwareWulf** [Meowlala/RepentanceAPIIssueTracker#334]
It was probably changed during the development and then forgotten about, the Trinket's name is Short Fuse, but it's TrinketType enum is called `TrinketType.TRINKET_FIRECRACKER`, I can see this being a bit confusing, so I suggest to rename this enum to `TrinketType.TRINKET_SHORT_FUSE`.

**Comment by Meowlala** [comment]
Confirmed fixed in 1.7.5.
