### ISSUE TITLE
ResourceExtractor filelist.txt hasn't been updated to add new files from 1.7.5 patch

### ISSUE THREAD

**Issue by namishere** [Meowlala/RepentanceAPIIssueTracker#348]
Primarily affects the new localization files, but also things from this update like new techstone, T. Eden nightmare portrait, new costumes, etc.

**Comment by Zamiell** [comment]
In the meantime you can use this to get the new files.
[filelist.txt](https://github.com/Meowlala/RepentanceAPIIssueTracker/files/7521260/filelist.txt)

**Comment by Meowlala** [comment]
Confirmed fixed in 1.7.6
