### ISSUE TITLE
Changing the starting room's character controls scheme for modded characters crashes the game

### ISSUE THREAD

**Issue by AwareWulf** [Meowlala/RepentanceAPIIssueTracker#349]
Since the newest update. all characters now have custom starting room controls scheme, but I couldn't figure out how to add these for modded characters, the ususal way of just putting the `controls.anm2` into the content folder and renaming `Controls` with the modded character's name doesn't work.

**Comment by im-tem** [comment]
it technically works but game crashes

**Comment by im-tem** [comment]
https://cdn.discordapp.com/attachments/846892870597869651/908334108856426496/start_drawing_sample.zip

here is a sample mod btw

**Comment by Meowlala** [comment]
Confirmed fixed in 1.7.6
