### ISSUE TITLE
TrinketType.TRINKET_FIRECRACKER and TrinketType.TRINKET_GIANT_BEAN were not kept as legacy variables

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#352]
Any mods that used the old variable names will be broken until they get updated (if they do). Not sure as to why they weren't added like the old ab+ enums which were kept for compatibility purposes.

**Comment by UnderscoreKilburn** [comment]
Because I forgot, whoops

**Comment by Meowlala** [comment]
Confirmed fixed in 1.7.6
