### ISSUE TITLE
Shaders still crash the game when reloading a mod and starting a run.

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#353]
I'm not exactly sure why this is a thing or if the fix would be simple or not. I just kinda assumed that when you reload mods from the menu it invokes whatever luamod calls on each mods, if this is how it works then I guess it could also call reloadshaders on all mods as well to prevent this crash.

I'm talking out of my ass though, maybe there's something bigger at hand, but it's still pretty annoying that people get a crash whenever they install a mod with shaders and similar situations, specially because they then complain about the crash on the mod's page and all that.

**Comment by Meowlala** [comment]
Duplicates #34
