### ISSUE TITLE
Calling Game:StartStageTransition make the game crash

### ISSUE THREAD

**Issue by Cuerzor** [Meowlala/RepentanceAPIIssueTracker#372]
My codes:
`local game = Game();`
`local level = game:GetLevel();`
`level:SetStage (LevelStage.STAGE6, StageType.STAGETYPE_ORIGINAL);`
`game:StartStageTransition(true, 0);`
I found it always crash the game, and the documentation says should call Init after Level:SetStage, but I cannot find any functions called Init.

**Comment by Meowlala** [comment]
Duplicates #137
