### ISSUE TITLE
MC_ITEM_PICKUP callback for when receiving a collectible

### ISSUE THREAD

**Issue by pedroff1** [Meowlala/RepentanceAPIIssueTracker#383]
One of the few callbacks I feel is sorely needed is one that triggers when the player picks up a collectible. While you can currently simulate one using ItemQueue, it does not work with items added via functions or the debug console. 
For that, I propose implementing the `MC_ITEM_PICKUP` callback:
As the callback argument, I propose it takes `CollectibleType`, working similar to `MC_USE_ITEM`, in that regards. And it should pass down the following function arguments (not necessarily in order):
`EntityPlayer player`, `int CollectibleType`, `bool FirstTimePickingUp`, `int ActiveSlot` and `int CustomVarData`

Optionally, returning values in it could have some effect, like maybe preventing the item to be added, or something similar.

**Comment by Meowlala** [comment]
Duplicates #215, I'll add this extra information in a comment.
