### ISSUE TITLE
Entity.SpawnerEntity is nil even when SpawnerType and SpawnerVariant are set

### ISSUE THREAD

**Issue by DarkestSentinel** [Meowlala/RepentanceAPIIssueTracker#42]
Entity.SpawnerType and Entity.SpawnerVariant work as intended and show the .Type and .Variant of the spawner of that entity, if that entity indeed has a spawner. It's odd for Entity.SpawnerEntity to be nil in that case.

**Comment by Meowlala** [comment]
Not always nil, but sometimes nil even when SpawnerType and SpawnerVariant are set.

**Comment by Meowlala** [comment]
I haven't been able to verify that this is fixed in the first rep API patch because I don't know how to reproduce it, but I'll close this for now unless it is found to be an issue again.
