### ISSUE TITLE
INIT callbacks of entities don't have the entity's position initialized yet

### ISSUE THREAD

**Issue by DarkestSentinel** [Meowlala/RepentanceAPIIssueTracker#43]
Entity.Position always returns Vector(0,0) in INIT callbacks and isn't useable for some of the needed calculations that an entity needs on init where position is relevant. This is bypassed using the first frame of the update callbacks in mods, which isn't ideal. It however is still possible to set the entity's position successfully in the INIT callbacks.

**Comment by Meowlala** [comment]
Duplicates #20
