### ISSUE TITLE
Item metadata tag "monstermanual" does not work with modded items

### ISSUE THREAD

**Issue by Zamiell** [Meowlala/RepentanceAPIIssueTracker#439]
If a modded item is given the "monstermanual" tag in the "items_metadata.xml" file, the modded item will still never appear when using Monster Manual.

**Comment by Xalum** [comment]
This isn't true.

https://streamable.com/935edu

**Comment by Zamiell** [comment]
Ok, I might have been testing incorrectly, so I will close this.
