### ISSUE TITLE
GridEntity Sprite attribute is not normally editable.

### ISSUE THREAD

**Issue by jsgnextortex** [Meowlala/RepentanceAPIIssueTracker#44]
The Sprite attribute of the GridEntity class acts in a pretty odd way. If you want to change the sprite rotation, lets say, doing Gent.Sprite.Rotation wont work...in order to achieve that you have to do the following currently:
```lua
local auxsprite = gent.Sprite
auxsprite.Rotation = newrotation
gent.Sprite = auxsprite
```
Which is unlike handling any other sprite in the api, It's like the get functions tosses you a copy of the GridEntity sprite rather than the actual reference?

**Comment by Meowlala** [comment]
It's also unusual that grid entities have a `.Sprite` rather than a `:GetSprite()` in the first place.

**Comment by jsgnextortex** [comment]
It would be cool if it had that, for consistency *cough*a GetData() would be bad either*cough*, but I could excuse that with the fact that GridEntities are very different from normal entities anyway.

**Comment by Meowlala** [comment]
Grid entities no longer have a `.Sprite` and now have a `:GetSprite` in the first rep API patch.
