### ISSUE TITLE
Box of Friends does not duplicate modded familiars properly

### ISSUE THREAD

**Issue by Zamiell** [Meowlala/RepentanceAPIIssueTracker#440]
They always result in Demon Baby (familiar variant 2) instead of the modded familiar variant

**Comment by Xalum** [comment]
This isn't true?

https://user-images.githubusercontent.com/43268652/155240424-ae02ff4f-49fa-46df-92cc-b8f4b4796ce3.mp4

**Comment by Zamiell** [comment]
Are you using CheckFamiliar?
All I'm doing is spawning a modded familiar, then using Box of Friends.
No Lua code is being executed.

**Comment by Xalum** [comment]
Yes, because that's how you're supposed to add familiars, all Box of Friends and Monster Manual do is increment the number of CollectibleEffects you have for a given familiar Item, that's how they work for base game familiars too

**Comment by Zamiell** [comment]
Hm, okay. The problem is that CheckFamiliar is bugged, but I guess I'll close this.
