### ISSUE TITLE
Color constructor wont allow floats for RO,GO,BO attributes

### ISSUE THREAD

**Issue by jsgnextortex** [Meowlala/RepentanceAPIIssueTracker#45]
The constructor of the Color class doesnt allow float values for the last 3 parameters (RO,GO,BO) even thought the actual values of the Color class can be floats and are used as floats.

**Comment by Meowlala** [comment]
This one's weird because RO-GO-BO take values 0-255 but are then converted into floats when used.

**Comment by jsgnextortex** [comment]
Yea, thats what I meant, but if you use methods like Colorize you'll notice that RO,GO and BO will take float values which makes it extremely tricky to copy colors unless you have the specific colorize parameters at the moement of copying.

**Comment by UnderscoreKilburn** [comment]
Would it be okay to simply change the constructor of the Color class to simply take values within the 0-1 range instead of 0-255? This would break existing mods that rely on the current behavior but at the very least it would be consistent.

**Comment by Meowlala** [comment]
It'd break a lot of mods, but a compatibility layer that just converts values above 1 to a 0-1 range would be pretty easy to write in LUA so another mod could potentially patch it. If old mods are going to break anyway due to changes to `FireTear` or similar then I'd say break it.

**Comment by Meowlala** [comment]
Has been adjusted and works as intended in Repentance's first API patch.
