### ISSUE TITLE
(pre api release) UseActiveItem/UseCard/UsePill crash the game.

### ISSUE THREAD

**Issue by jsgnextortex** [Meowlala/RepentanceAPIIssueTracker#46]
Using any of the "Use" functions on the EntityPlayer class (UseActiveItem/UseCard/UsePill) will crash the game on the pre-api repentance build (not sure if we should be adding these here but it may be useful for tracking).

**Comment by Meowlala** [comment]
Verified all three to work as they should in repentance's first API patch.
