### ISSUE TITLE
Saving and continuing in a temporary room crashes the game/bricks save file

### ISSUE THREAD

**Issue by ngregrichardson** [Meowlala/RepentanceAPIIssueTracker#476]
**Description**
If you are in a temporary room and you exit the game, then continue, the game crashes and the save is not recoverable.

**Expected**
The game either saves the temporary room you were in or puts you into the last regular room you were in.

**To Reproduce**
1. Start a new run
2. Run "goto s.supersecret.1" or go to any other temporary room
3. Go to the menu and exit the game
4. Continue and the game crashes.

**Additional**
I found this while making a mod that is using primarily temporary rooms, but this stands in the way of that. I did try a few workarounds, like teleporting the player to the starting room in the MC_PRE_GAME_EXIT callback, but no such luck.

**Comment by Xalum** [comment]
This duplicates #109

**Comment by ngregrichardson** [comment]
> This duplicates #109

Didn't see that, thanks!
