### ISSUE TITLE
MakeRedRoomDoor allows creating doors that should be illegal

### ISSUE THREAD

**Issue by laceous** [Meowlala/RepentanceAPIIssueTracker#483]
I would expect this function to follow the same rules as the red key. It seems more permissive though.

It's possible to create doors leading to I AM ERROR rooms in the middle of the map. For example:
* On door slots that aren't valid for a certain room shape. The door will show up partially in the middle of the room.
* At the mirror entrance, which overrides the mirror with a door to an error room.
* At door slots where there can't be an adjacent room, like boss rooms.

**Comment by im-tem** [comment]
i think it should have a "Force" argument which would create red room regardless of whether layout allows it or not

**Comment by catinsurance** [comment]
This behavior doesn't happen anymore as of v1.7.9b
