### ISSUE TITLE
Missing entry in the EntityType Enum List

### ISSUE THREAD

**Issue by Howard-Hehengchi** [Meowlala/RepentanceAPIIssueTracker#496]
The enemy entity "Mr. Mine", whose id is supposed to be 311.0.0 according to the wiki, is not listed in the EntityType list.

**Comment by epfly6** [comment]
Nah, it's listed
![image](https://user-images.githubusercontent.com/36567300/167460852-79c06074-444a-4ac9-a55d-d73de7d61455.png)
