### ISSUE TITLE
Replacing spritesheets does not work for player entity's Sprite

### ISSUE THREAD

**Issue by im-tem** [Meowlala/RepentanceAPIIssueTracker#51]
How to reproduce:
* Isaac.GetPlayer(0):GetSprite():ReplaceSpritesheet(spritesheet_id, path_to_png)
* Isaac.GetPlayer(0):GetSprite():LoadGraphics()

Expected outcome:
* Provided spritesheet is used instead of default option.

Result:
* Spritesheet does not get replaced.

Note:
* Other Sprite class operations (e.g. Sprite:Load) work fine on player's sprite, this is an exception.

Demonstration:
* https://user-images.githubusercontent.com/18075164/117284070-2331c800-ae6f-11eb-960a-c785bf7cfe83.mp4

**Comment by Meowlala** [comment]
This isn't true. The issue you're running into is that `ReplaceSpritesheet`'s first argument is the layer of the sprite to replace, not the ID of the spritesheet being replaced.

If you replaced 12, 4, and 1, which are the layers that use the full player sheet, instead, this would work fine.

**Comment by im-tem** [comment]
I am sorry! Was thrown off by the name of the function
