### ISSUE TITLE
EntityTear.Bounced always returns nil

### ISSUE THREAD

**Issue by TiredFoks** [Meowlala/RepentanceAPIIssueTracker#524]

**Comment by catinsurance** [comment]
[This was seemingly removed with Repentance, according to my testing and the community documentation.](https://wofsauge.github.io/IsaacDocs/rep/EntityTear.html#bounced)

![kitty_v1dBsJZFaf](https://github.com/epfly6/RepentanceAPIIssueTracker/assets/65452914/e55e1c8f-0db4-4578-8b0a-82dc4757a5d4)

I'm going to close this, a separate issue can be opened for a feature request if you want it brought back.
