### ISSUE TITLE
My hearts and map don't show up

### ISSUE THREAD

**Issue by RandyRenegade** [Meowlala/RepentanceAPIIssueTracker#547]
Just what the title says. I know this is a mod issue because it doesn't happen when I turn off all the mods, and its only been a problem since the latest update. Restarting doesn't fix it either. I don't know which mod it is, I haven't disabled them one at a time to test yet, but I probably will if nobody knows which of my mods is responsible. The list of mods I have installed with an * if I've already tried deactivating them:

-Retribution - 160 Items!
-Visible Fortune
-Infini-Chest!
-DBZ teleport
-Redemption Community Pack
-Repentance Boss Champions - Fiend Folio Compatibility
-Repentance Boss Champions
-[REP]Pokemon Resprites
-Arcade Machines Resprites 2 - Armegeddon
-[REP]Improved Chargebars
-Fiend Folio: Reheated - 500 New Monsters!
-Custom Stage API
-arcade machine resprites
-A Pony Synergies!
-Options Resprite
-better pooters
-Boss Rush Wave Counter [Rep | AB+]
-Da Rules - A Sandbox Menu Thingy [REP/AB+]*
-Explorite utility
-Fancy Costumes
-Worm Item Resprites
-Extra animated portraits
-Jacob & Esau: Dual Flight
-Jacob's Ladder Synergies
-GoodTrip[Repentance/AB+]*
-Mantle Rework
-Unique Birthright Sprites
-Rainbow Poop Gives a Soul Heart
-White Fireplace Icon
-[AB+|Rep] MiniMAPI: A Minimap API*
-Akeldama Synergy
-[REP] Binding of Isaac: Epiphany (Tarnished Characters)
-Mod Config Menu - Continued
-Mod Compatibility Hack
-Encyclopedia - An In-Game Wiki
-Luckier Pennies
-Item Pedestal Overhaul
-Animated Costumes (Rep) + Adding More
-Better Bombs
-Planetarium Chance
-[AB+|Rep] External item descriptions
-[REP] Andromeda (+28 Unlocks)
-Mega Mush CostumeSuffix Compat
-Rare Super Secret Rooms! (100+ rare super secret rooms to find!)
-Fredd's character portraits
-Gurgle Resprite
-Hush Resprite
-The Deleted
-Rare Secret Rooms! (115+ rare secret rooms to find!)
-Unique Megaisaacs
-Boss Portrait Overhaul
-Pretty Princess! (Leech Resprite Mod)
-Lump Fix
-[Rep] Enhanced Boss Bars
-Animated Items

**Comment by MrSeemsGood** [comment]
this should be closed. yes it is a mod issue, but it shouldn't be posted here, at least not until you've tried to find the culprit **on your own**. different mods can break different other mods in different ways since 1.7.9b, we can only hope that there is a universal solution for this mess coming in the next patch.

**Comment by Zamiell** [comment]
@RandyRenegade please close this issue
