### ISSUE TITLE
Suggestion: PillColor could've be a part of MC_USE_PILL callback (For horsepill and effects on pill color)

### ISSUE THREAD

**Issue by ProjectTZ** [Meowlala/RepentanceAPIIssueTracker#558]
![image](https://user-images.githubusercontent.com/36955404/230463423-ecefb0ec-cd09-4b7a-a05a-4a2471342bc8.png)
It's really hard to track Horsepills, as there is no proper callback in the MC_USE_PILL which would've activate on color/size of used pill

**Comment by epfly6** [comment]
Duplicate of #275 and #451

**Comment by Zamiell** [comment]
@ProjectTZ please close this issue
