### ISSUE TITLE
 [REP+] Mods won't work if the "Documents" folder is in a different location.

### ISSUE THREAD

**Issue by NiHuShu** [Meowlala/RepentanceAPIIssueTracker#572]
In order to use mods with the new Repentance+ update, mods should be placed in the "C:\Users\[YourUserName]\Documents\My Games\Binding of Isaac Repentance+\mods\" folder. 

However, in my case, the game decided to create the "Documents" folder inside the main game directory. So, in my case the path looks like this "C:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth\Documents\My Games\Binding of Isaac Repentance+\mods". 

The game definitely sees that folder as it has the "warning.txt" file, and if I put mods inside, they do appear in the game. However, all mod names are just the names of their folders + they don't actually do anything. 

![Screenshot 2024-11-22 110439](https://github.com/user-attachments/assets/f4c3cd8b-6555-436a-93be-72638fc4d529)

It happens even with mods that have been already updated to support REP+ like EID.

**Comment by jerbmega** [comment]
Fixed in 1.9.7.6, which reverts back to Repentance's mods folder
