### ISSUE TITLE
[REP+] HUD.ShowItemText stays onscreen forever

### ISSUE THREAD

**Issue by laceous** [Meowlala/RepentanceAPIIssueTracker#573]
Game():GetHUD():ShowItemText('hello', 'world', false)

The text doesn't auto-dismiss itself like it used to. You have to quit/continue to get rid of it. ShowFortuneText appears to work correctly.

**Comment by jsgnextortex** [comment]
Adding on to this, if you fill the screen with perma streaks and restart the run, no streaks will show up until you restart the game.

**Comment by epfly6** [comment]
Fixed in v1.9.7.7
