### ISSUE TITLE
[Rep+] Familiars Alpha Value is ignored

### ISSUE THREAD

**Issue by jsgnextortex** [Meowlala/RepentanceAPIIssueTracker#577]
No matter what you set a familiar Color Alpha value it will remain fully solid and visible. This wasnt the case prior and it makes it impossible to make semi-transparent familiars or many familiars go in and out of translucency with ease. I also tried setting the color on the Sprite directly, instead of on the familiar property, but the result remains the same, it is either being reset to 1 or not being assigned at all by the API.

**Comment by laceous** [comment]
I had to update one of my mods that was setting an offset color like this (in Rep):

entity:GetSprite().Color:SetOffset(...)

to this (in Rep+):

entity:GetSprite().Color = Color(r,g,b,a,...)

It seemed like the color property had become read-only. Not sure if that was intended or not.

SetOffset still seems to work on a Color object that I create.

**Comment by jsgnextortex** [comment]
The alpha value wont change even when doing entity:GetSprite().Color = Color(r,g,b,a,...), so yours sounds like an unrelated issue. R,G,B,RO,GO and BO will change, however, its just the alpha thats fucked.

**Comment by epfly6** [comment]
Fixed in v1.9.7.7
