### ISSUE TITLE
[REP+] REPENTANCE global value is missing

### ISSUE THREAD

**Issue by NAT0P0TAT0** [Meowlala/RepentanceAPIIssueTracker#580]
this is breaking lots of mods that check for repentance specific features

adding the REPENTANCE_PLUS value is good, but there are many mods that are compatible with rep+ that are now going to have problems and they definitely won't all be updated so people will be missing out on mods that should have been fine

both globals should be present in rep+

**Comment by epfly6** [comment]
Added back in v1.9.7.8
