### ISSUE TITLE
[REP+] HUD.ShowItemText should have an override argument

### ISSUE THREAD

**Issue by ddeeddii** [Meowlala/RepentanceAPIIssueTracker#581]
Since this function got changed in `v1.9.7.7` it now stacks the displayed text in a column, as opposed to its previous functionality where it just displayed new text on top of whatever other item text was present.
An override argument in the function that allows the new displayed text to have the old functionality of just being on top of everything would be nice

**Comment by epfly6** [comment]
Added in v1.9.7.8. From official blogpost:
```HUD.ShowItemText now has a new parameter (for both versions of the function). if this new value is missing or true then it clears the message stack (legacy functionality). if it's false then they stack up (Rep+ functionality)```
