### ISSUE TITLE
Number multiplied by Entity.SizeMulti causes an error

### ISSUE THREAD

**Issue by catinsurance** [Meowlala/RepentanceAPIIssueTracker#582]
Multiplying any number by an Entity's `SizeMulti` property causes an error. Note that if multiplying it the other way around (`SizeMulti` first and then number), it functions properly.

![kitty_5vfoRyf9ua](https://github.com/user-attachments/assets/69e74057-2d0e-4763-be8d-eec48b638cb0)

**Comment by epfly6** [comment]
Fixed in v1.9.7.8
