### ISSUE TITLE
Existing calls to Room:DamageGrid() and Room:DestroyGrid() error with "EntityRef expected"

### ISSUE THREAD

**Issue by ConnorForan** [Meowlala/RepentanceAPIIssueTracker#583]
Similar to the [previously fixed issue with GridEntity:Destroy()](https://github.com/epfly6/RepentanceAPIIssueTracker/issues/568), existing usage of these functions error due to expecting an EntityRef parameter that was not previously required.

It would be good for backwards compatibility if wrappers were added to these functions as was done for GridEntity:Destroy() and Entity:Kill(), or if the new parameters were made optional.

![image](https://github.com/user-attachments/assets/db973009-3b6a-4d88-a0da-c8e8cb43911b)

DestroyGrid in particular seems to have actually gained two new parameters. Ideally both would still be optional, whatever the new one before the EntityRef is.

![image](https://github.com/user-attachments/assets/19e8111e-319a-4ca1-b944-79fc6b7143ca)

**Comment by epfly6** [comment]
Fixed in v1.9.7.8. Added DestroyGridWithSource and DestroyGridWithSource methods which requires EntityRef pass
