### ISSUE TITLE
Existing calls to GridEntity:Hurt() error with "EntityRef expected"

### ISSUE THREAD

**Issue by ConnorForan** [Meowlala/RepentanceAPIIssueTracker#584]
Similar to the [previously fixed issue with GridEntity:Destroy()](https://github.com/epfly6/RepentanceAPIIssueTracker/issues/568), existing usage of this function errors due to expecting an EntityRef parameter that was not previously required.

It would be good for backwards compatibility if a wrapper was added to this functions as was done for GridEntity:Destroy() and Entity:Kill(), or if the new parameters was made optional.

![image](https://github.com/user-attachments/assets/0be60db8-6750-46ac-973f-15ae1385193a)

**Comment by epfly6** [comment]
Fixed in v1.9.7.8. HurtWithSource method was added, where it requires EntityRef pass
