### ISSUE TITLE
Ability to modify the damage/tears stats in the same manner as the basegame

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#60]
Currently, if you want to make a damage or tears item, you can only modify the Damage and MaxFireDelay attributes after everything has been calculated. However, many of the damage and tears items in the game abide by specific rules when modifying these stats. The most standard of these are the basic "Damage Up" and "Tears Up" items like Pentagram and Sad Onion, which get applied via diminishing returns and, in the case of tears, soft caps. Currently, if you want to add items that abide by these same rules, you either have to try and make up the difference by giving the player stat items/temporary effects/pill effects, or you have to recreate the entire damage/tear formula. It would be useful, then, if we had some sort of access to these interim damage/tears formula values.

**Comment by Meowlala** [comment]
Duplicates #7
