### ISSUE TITLE
Allow for adding custom item/enemy portraits

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#62]
Currently, the only way to give an enemy a portrait (what's used for the bestiary, death note, dreamcatcher, etc) is to override the vanilla portrait anm2, this is super incompatible between mods

A proposed solution would be to allow the specification of a custom portraits anm2 in the entity's xml entry, and then the currently existing portrait tag would indicate the frame number in this anm2

As an extension there should also be a way to do the same for items, especially as their portraits are used more blatantly as 🅱️ethany's wisps

**Comment by Meowlala** [comment]
Not sure if this is a duplicate, but closely related to #16

**Comment by Xalum** [comment]
This was fixed a couple of patches ago
