### ISSUE TITLE
Allow for modifying player stats in the same way the base game does

### ISSUE THREAD

**Issue by Meowlala** [Meowlala/RepentanceAPIIssueTracker#7]
The base game uses various features to taper the effects of Damage and Tears upgrades, which we do not have access to.

The base game's formulas (or at least an accurate reimplementation of them) for the [Damage](https://bindingofisaacrebirth.fandom.com/wiki/Damage) and [Tears](https://bindingofisaacrebirth.fandom.com/wiki/Tears) stats can be found on the Isaac wiki.

We are missing access to:

- The base damage stat that enters the formula
- The overall damage multiplier
- The base tears stat that enters the formula
- The current tears cap (adjusted for things like soy milk)
- The new repentance range stat

**Comment by TaigaTreant** [comment]
According to https://bindingofisaacrebirth.fandom.com/wiki/Damage, the damage formula (excluding multipliers) is as follows:

`EffectiveDamage = CharBaseDmg x math.sqrt(DiminishingDamageUps x 1.2 + 1) + FlatDamageUps`

As such, it would be nice to have the following values exposed in EntityPlayer to assist in modifying the damage stat and maintaining compatibility with other mods:

- `EntityPlayer.CharacterBaseDamage`: 3.5 for most characters, not including the character specifc damage multipliers
- `EntityPlayer.DiminishingDamage`: The total value of diminishing damage ups the player currently has (Pentagram, 8 Inch Nails, Lusty Blood, Blood Oath, Dogma, etc.), including Odd Mushroom (Thin)'s damage multiplier as it is applied before diminishing occurs.
- `EntityPlayer.TotalDamageMultiplier`: The total multiplier applied to damage after diminishing has occurred (Soy Milk, Magic Mushroom, D8, character damage multipliers, etc.), not including Odd Mushroom (Thin)'s damage multiplier as it is applied before diminishing occurs.

**Comment by Meowlala** [comment]
Adjusting this to high priority temporarily for the Range stat, which is currently entirely inaccessible.

**Comment by Meowlala** [comment]
Range stat is fixed in 1.7.5, the rest of this enhancement needs rewording since the base game's stats don't really work in a consistent way like it suggests.
