### ISSUE TITLE
XML tag indicating single-use active items

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#71]
XML support for single-use active items was not explicitly necessary until the rework to the Void item, as it now waits until its next use to proc a single-use item. Previously it was possible to remove modded single-use actives on Void's PRE_USE callback and manually trigger their use, however since copies of the Void item track their item storage individually, issues may arise when implementing a workaround to fit with the new logic

**Comment by Meowlala** [comment]
`EntityPlayer:RemoveCollectible` was updated and features "IgnoreModifiers: Ignores collectible effects granted by other items (i.e. Void)", does that resolve this issue?

`MC_USE_ITEM` was also updated and allows returning a table with `Remove = true` set, does that resolve this issue?

**Comment by Xalum** [comment]
MC_USE_ITEM new return values works perfectly, this issue is resolved
