### ISSUE TITLE
Active item costumes are only applied once the active item is used

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#84]
When tying a costume to an active item, it will only be applied once the active item is used. This even applies to the EntityPlayer:AddCostume() function. This slightly complicates the ability to add costumes to active items that are applied simply by being held, requiring use of null costumes.

**Comment by Meowlala** [comment]
Does the new `passivecache="true"` flag on active items fix this?

**Comment by UnderscoreKilburn** [comment]
`addcostumeonpickup="true"` should cover this

**Comment by Meowlala** [comment]
Verified that `addcostumeonpickup="true"` works.
