### ISSUE TITLE
Ability to start playing a sprite animation starting from a specific frame

### ISSUE THREAD

**Issue by TaigaTreant** [Meowlala/RepentanceAPIIssueTracker#85]
Currently, there is no way to start playing a sprite animation starting from a specific frame; Play() forces it to start from the first frame. You can use SetFrame() to go to a specific frame, but it pauses the animation. As such, it would be useful if we could select a specific frame to start animation from, perhaps as an argument to be passed to the Play() function.

**Comment by Meowlala** [comment]
In patch, `Sprite:SetFrame(int Frame)` without specifying animation sets the frame of the current animation without stopping it, which should cover this.

**Comment by Meowlala** [comment]
Verified to be functioning in the first rep API patch.
