### ISSUE TITLE
The luamod console command does not work if the main.lua uses require()

### ISSUE THREAD

**Issue by Zamiell** [Meowlala/RepentanceAPIIssueTracker#9]
Every medium-to-large mod uses `require()` in order to break up their mod into separate files.
So, this bug makes testing mods a pain in the ass, forcing an entire game reload.
The luamod console command is also utilized by automatic-mod-reloading tooling, such as in [IsaacScript](https://isaacscript.github.io/).

**Comment by Meowlala** [comment]
As a note, this is because of some LUA package caching that occurs behind the scenes when require is used. With luadebug enabled, this can be fixed by setting `package.loaded[name] = false` to prevent loading from cache.

**Comment by Meowlala** [comment]
`require` can now be replaced with `include` as of rep's first API patch, which is verified to work without this issue.

**Comment by Zamiell** [comment]
Did you test with require?

**Comment by Meowlala** [comment]
require works the same way it did before the patch.

**Comment by Zamiell** [comment]
I did a simple mod that required another file and I did `luamod test` and I didn't get any errors. Was there something more complicated to produce the error in Afterbirth+ or was it fixed in Repentance?

**Comment by Meowlala** [comment]
It never caused errors, it simply wouldn't load any changes made to the required file after the initial launch.

**Comment by Zamiell** [comment]
Oh, I see, because it caches.
