### ISSUE TITLE
Allow EntityProjectile.Scale to be increased without automatically increasing the dealt damage of the projectile

### ISSUE THREAD

**Issue by Xalum** [Meowlala/RepentanceAPIIssueTracker#97]

**Comment by Meowlala** [comment]
This is specifically the damage the projectile deals to the player right?

**Comment by Xalum** [comment]
I actually don't know how it affects charmed damage against other monsters, but yeah the player specifically is the big gripe

**Comment by Xalum** [comment]
Increasing projectile.Scale no longer auto-increases dealt damage in the repentance api patch
